### ISSUE TITLE
Could you please tell me how to get the Sulzberger data set II?

### ISSUE THREAD

**Issue by ilixinyu** [summitgao/SAR_Change_Detection_CWNN#1]
Could you please tell me how to get the Sulzberger data set II?
I noticed that your article used the Sulzberger data set II to compare related methods. However, I  can not find it through the repositories. Could you please submit it or give us a website to download it?

**Comment by summitgao** [comment]
In our recent work, some reviewers comment that the the ground truth labels of Sulzberger dataset are not accurate enough. Hence, we do not plan to release the dataset.

**Comment by Mr-ZhangJin** [comment]
Hi，Sir. Today，could you please tell me how to get the Sulzberger data set II?
